const LOAD_CUR_FILM_COMMENTS = `app/comments/LOAD_CUR_FILM_COMMENTS`;
const INIT_POST_COMMENT_ERROR = `app/comments/INIT_POST_COMMENT_ERROR`;
const RESET_POST_COMMENT = `app/comments/RESET_POST_COMMENT_ERROR`;
const SET_POST_COMMENT_SUCCESS = `app/comments/SET_POST_COMMENT_SUCCESS`;

export default {
  LOAD_CUR_FILM_COMMENTS,
  INIT_POST_COMMENT_ERROR,
  RESET_POST_COMMENT,
  SET_POST_COMMENT_SUCCESS
};
