const SHOW_MORE_FILMS = `app/movie-list/SHOW_MORE_FILMS`;
const SET_DISPLAYED_FILMS_AMOUNT = `app/movie-list/SET_DISPLAYED_FILMS_AMOUNT`;

export default {
  SHOW_MORE_FILMS,
  SET_DISPLAYED_FILMS_AMOUNT
};
