const SET_APP_IS_READY = `app/SET_APP_IS_READY`;
const OPEN_VIDEO_PLAYER = `app/OPEN_VIDEO_PLAYER`;
const CLOSE_VIDEO_PLAYER = `app/CLOSE_VIDEO_PLAYER`;
const INIT_SETUP_APP_ERROR = `app/INIT_SETUP_APP_ERROR`;
const IDENTIFY_EDGE_BROWSER = `app/IDENTIFY_EDGE_BROWSER`;
const RESET_SETUP_APP_ERROR = `app/RESET_SETUP_APP_ERROR`;


export default {
  SET_APP_IS_READY,
  OPEN_VIDEO_PLAYER,
  CLOSE_VIDEO_PLAYER,
  INIT_SETUP_APP_ERROR,
  RESET_SETUP_APP_ERROR,
  IDENTIFY_EDGE_BROWSER
};

