const SET_APP_IS_READY = `app/SET_APP_IS_READY`;
const OPEN_VIDEO_PLAYER = `app/OPEN_VIDEO_PLAYER`;
const CLOSE_VIDEO_PLAYER = `app/CLOSE_VIDEO_PLAYER`;

export default {
  SET_APP_IS_READY,
  OPEN_VIDEO_PLAYER,
  CLOSE_VIDEO_PLAYER
};

