const SET_AUTH_SUCCESS = `app/user/SET_AUTH_SUCCESS`;
const SET_AUTH_REQUIRED = `app/user/SET_AUTH_REQUIRED`;
const INIT_AUTH_SERVER_ERROR = `app/user/INIT_AUTH_SERVER_ERROR`;
const RESET_AUTH_ERRORS = `app/user/RESET_AUTH_ERRORS`;

const SET_USER_PROFILE = `app/user/SET_USER_DATA`;
const SET_USER_MY_LIST = `app/user/SET_USER_MY_LIST`;
const SET_MY_LIST_LOADED = `app/user/SET_MY_LIST_LOADED`;
const ADD_FILM_TO_MY_LIST = `app/user/ADD_FILM_TO_MY_LIST`;
const DEL_FILM_FROM_MY_LIST = `app/user/DEL_FILM_FROM_MY_LIST`;
const INIT_FAVORITE_ERROR = `app/user/INIT_FAVORITE_ERROR`;
const SET_FAVORITE_SUCCESS = `app/user/SET_FAVORITE_SUCCESS`;
const RESET_FAVORITE_ERROR = `app/user/RESET_FAVORITE_ERROR`;
const CLEAR_USER_DATA = `app/user/CLEAR_USER_DATA`;


export default {
  SET_AUTH_SUCCESS,
  SET_AUTH_REQUIRED,
  INIT_AUTH_SERVER_ERROR,
  RESET_AUTH_ERRORS,
  SET_USER_PROFILE,
  SET_USER_MY_LIST,
  CLEAR_USER_DATA,
  ADD_FILM_TO_MY_LIST,
  DEL_FILM_FROM_MY_LIST,
  INIT_FAVORITE_ERROR,
  SET_FAVORITE_SUCCESS,
  RESET_FAVORITE_ERROR,
  SET_MY_LIST_LOADED
};
