const SET_AUTH_SUCCESS = `app/user/SET_AUTH_SUCCESS`;
const SET_AUTH_REQUIRED = `app/user/SET_AUTH_REQUIRED`;
const INIT_AUTH_SERVER_ERROR = `app/user/INIT_AUTH_SERVER_ERROR`;
const RESET_AUTH_ERRORS = `app/user/RESET_AUTH_ERRORS`;

const SET_USER_PROFILE = `app/user/SET_USER_DATA`;
const SET_USER_MYLIST = `app/user/SET_USER_MYLIST`;
const CLEAR_USER_DATA = `app/user/CLEAR_USER_DATA`;


export default {
  SET_AUTH_SUCCESS,
  SET_AUTH_REQUIRED,
  INIT_AUTH_SERVER_ERROR,
  RESET_AUTH_ERRORS,
  SET_USER_PROFILE,
  SET_USER_MYLIST,
  CLEAR_USER_DATA
};
