const SHOW_MORE_FILMS = `app/catalog/SHOW_MORE_FILMS`;
const SET_DISPLAYED_FILMS_AMOUNT = `app/catalog/SET_DISPLAYED_FILMS_AMOUNT`;

export default {
  SHOW_MORE_FILMS,
  SET_DISPLAYED_FILMS_AMOUNT
};
